"""
Django settings for BaseModule project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import Admin

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0dw4_35*=i-ccn3m&h3u61$l5)-3n2#*xn2kjmc5x4m_ec*nvt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'BaseApp',
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    'Admin',
    'django_cron'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'BaseModule.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "static", "templates"),
                 os.path.join(BASE_DIR, "static", "static", "app")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BaseModule.wsgi.application'
# Email gateway configuration
"""EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.mandrillapp.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'devendra@anipr.in'
EMAIL_HOST_PASSWORD = 'SBCiOWQ0lN1Z9MdTIY1Sbg'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'"""

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'raythumithra',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': ''
    }
}

# facebook app configuration

FACEBOOK_APP_ID='1566678290273052'
FACEBOOK_API_SECRET='a9d11b9a1cd709af315fd35211fb05ba'


# Google Secret key
GOOGLE_SECRET = "t2Yy54S4YS7646ntT1nnvYyo"

# Twitter app configuration
TWITTER_CONSUMER_KEY = "bKShd2R55i5LntkOqmuMJL0df"
TWITTER_CONSUMER_SECRET = "PDVLrPjFgEwOHZn5SWdestr7B7A2zfgRJy034rlynTTKZSIiY5"
TWITTER_CALLBACK_URL = "127.0.0.1:8000"


# Linkedin app configuration
LINKEDIN_SECRET = "dk1Eyj1Rfn7kuNIl"

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT=os.path.join(BASE_DIR,"static/")

STATICFILES_DIRS = (
        os.path.join(BASE_DIR, "static", "static"),
        os.path.join(BASE_DIR, "uploads")
    )


# Accessing auth user

AUTH_USER_MODEL = 'auth.User'


# Push notification config
PUSH_NOTIFICATIONS_SETTINGS = {
        "GCM_API_KEY": "AIzaSyBonBGRYW76jbskip1p75k5Uxx4qNWnsRY",
        "GCM_POST_URL" : "https://android.googleapis.com/gcm/send",
        "GCM_MAX_RECIPIENTS" : 1000,
}

CRON_CLASSES = [
    "Admin.views.MyCronJob"
]

#import django
#django.setup()

